### ISSUE TITLE
Please add .gitignore file

### ISSUE THREAD

**Issue by yusuke024** [smartVong/4square#1]
This repo doesn't have a _.gitignore_ file and result in having so many files that shouldn't be tracked tracked.

For example, the files below shouldn't be tracked because it's specific to your machine's environment which is not good for collaboration. 

![_users_sam_developer_scratchpad_4square__git_](https://cloud.githubusercontent.com/assets/3662104/7295999/adadd8d4-e9e5-11e4-916c-efbc621e3706.png)

You can find a well-compiled, community-curated list of _.gitignore_ files at https://github.com/github/gitignore

**Comment by smartVong** [comment]
I've done some tweaking to the repo, it's ok now?

**Comment by yusuke024** [comment]
Nicely done rub
